### ISSUE TITLE
作业

### ISSUE THREAD

**Issue by GitHubZian** [QZHY-HTX/Data-Structure#5]
#include<stdio.h>
// 定义结构体
struct stu
{
    char id[20];
    float score;
};
int main(){
    struct stu student[5] ={
        {"10001",98},{"10002",83},{"10003",44},{"10004",34},{"10005",67}
    };
    const int n = 5; ////n为同学数量 设为5
    struct stu temp; ////定义结构体临时变量
    // 比较高低
    int i,j,k;
    for(i = 0;i<n-1;i++){
        k = i;
        for(j = i + 1;j<n;j++){
            if(student[j].score > student[k].score)
            k = j;
            temp = student[k];
            student[k] = student[i];
            student[i] = temp;
        }
    }

    //计算平均数和不及格人数 
    float avg,sum;  //avg:平均数；sum:临时总数
    int lower_stu_num = 0;   //lower_stu_num:不及格人数
    for(i = 0;i<n;i++){
        sum += student[i].score;
        if(student[i].score <=60.0)
            lower_stu_num +=1;
        } 
    avg = sum / n;

    //  输出
    for(i = 0;i<n;i++)
        printf("%s %.2f\n",student[i].id,student[i].score);
    printf("%.2f %d",avg,lower_stu_num);
    return 0;
}
这个是不是提交issue？祥哥？

**Comment by QZHY-HTX** [comment]
是的，这个叫做提交 issue，但是要注意表达方式，请使用 markdown 标准语法，例如，代码块高亮，否则不好观看，给你一个示例：

```c
#include<stdio.h>
int main(){
    return 0;
}
```
